### ISSUE TITLE
Move parsers from baseclasses in to plugins

### ISSUE THREAD

**Issue by RoteKekse** [nomad-hzb/nomad-chemical-energy#11]

**Comment by carla-terboven** [comment]
I am not exactly sure what to do. You moved the necc_excel_parser.py file from the helpers directory in the baseclasses to the nomad-chemical-energy repository. What should be done to solve this issue?

**Comment by RoteKekse** [comment]
identify all parsers in https://github.com/nomad-hzb/nomad-baseclasses/tree/main/baseclasses/helper/file_parser which are used in this repo and move the files here and correct the input statements :).

**Comment by carla-terboven** [comment]
Oh I was still in the NECC bubble. Ok now I understand :D
