### ISSUE TITLE
Multiple files with same extension linked to a sample

### ISSUE THREAD

**Issue by anak-velazquez** [nomad-hzb/nomad-chemical-energy#21]
Enable to link more than 1 file with the same extension to a sample for the graph view

**Comment by carla-terboven** [comment]
I edited the jupyter notebook. When the files/nomad-entries have different names they can can show up even if they have the same extension. You can check here: https://nomad-hzb-ce.de/nomad-oasis/gui/user/uploads/upload/id/iDAClRy8R7KkoYL69JJn_A/files/catlab_samples.ipynb
Not sure how to proceed. Maybe you can update the ipnb file in the upload you share with Lukas?
