### ISSUE TITLE
Display name/label on sample node instead of the ID

### ISSUE THREAD

**Issue by anak-velazquez** [nomad-hzb/nomad-chemical-energy#22]
Display a label on sample node (blue nodes) instead of the sample ID, so it's easier to visualize what was the process that this sample was subjected to. Which labels to use, to be addressed. ATM we could display the name of the sample, maybe?

**Comment by carla-terboven** [comment]
Should be fixed in https://nomad-hzb-ce.de/nomad-oasis/gui/user/uploads/upload/id/iDAClRy8R7KkoYL69JJn_A/files/catlab_samples_20240930.ipynb
