### ISSUE TITLE
Add default parsing to CE Nome parser

### ISSUE THREAD

**Issue by RoteKekse** [nomad-hzb/nomad-chemical-energy#30]
Any file which starts with a valid cenome id shpuld be mapped to a general measurement :)

https://github.com/nomad-hzb/nomad-chemical-energy/blob/6456cb3de6f0226c0379375d079fec9a571b6b27/src/nomad_chemical_energy/schema_packages/ce_nome_package.py#L1280

**Comment by carla-terboven** [comment]
There were also ideas to rename the GeneralMeasurement. Should this also happen in this context? If so, what should it be called? GeneralProcess? Or do we stick with GeneralMeasurement?

**Comment by RoteKekse** [comment]
Lets go with GeneralProcess
