### ISSUE TITLE
Voila Notebook description column not working

### ISSUE THREAD

**Issue by carla-terboven** [nomad-hzb/nomad-chemical-energy#37]
If a description is entered it is not saved in the entry and it disappears from the table. The column should be saved correctly like the other columns.

**Comment by carla-terboven** [comment]
[This](https://nomad-hzb-ce.de/nomad-oasis/gui/user/uploads/upload/id/iDAClRy8R7KkoYL69JJn_A/entry/id/8nMfIJA78QOXnY0-VUINO17D-NVE/files/catlab_samples_20241030.ipynb) should solve the issue. Please check @anak-velazquez .

**Comment by anak-velazquez** [comment]
works perfect, thanks!
